version: "3.7"

services:
    # image project
    app-modelo:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-modelo
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # nginx
    nginx-modelo:
        image: nginx:alpine
        container_name: nginx-modelo
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db-modelo:
        image: mysql:8
        container_name: db-modelo
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge